//Exception Handling Mechanism

#include <iostream>
using namespace std;

int main() {
    try {
        int a = 10, b = 0;
        if (b == 0) throw "Division by zero!";
        cout << a / b;
    } catch (const char *msg) {
        cout << "Error: " << msg << endl;
    }
    return 0;
}
